import React, { useEffect, useState } from 'react';
import { AdminCustomer, platformService } from '@/services/platformService';

const CustomerUsersPage: React.FC = () => {
  const [users,setUsers]=useState<AdminCustomer[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=()=>platformService.adminUsers().then(setUsers).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load customers.')).finally(()=>setLoading(false));
  useEffect(()=>{void load();},[]);
  const change=async(user:AdminCustomer)=>{await platformService.updateCustomerStatus(user.id,user.status==='active'?'disabled':'active');await load();};
  return <div className="space-y-6"><div><h1 className="text-2xl font-black text-gray-950 dark:text-white">Customer Accounts</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Safe operational account information. Session, OTP, recovery, and purchase tokens are never shown.</p></div><div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800">{loading?<p className="p-8">Loading customers…</p>:error?<p className="p-8 text-red-600 dark:text-red-400">{error}</p>:users.length===0?<p className="p-8 text-gray-500">No customer accounts yet.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500 dark:bg-gray-900/60 dark:text-gray-400"><tr><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Joined / activity</th><th className="px-5 py-4">Orders / requests</th><th className="px-5 py-4">Paid total</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-gray-700">{users.map(user=><tr key={user.id}><td className="px-5 py-4"><strong className="block text-gray-950 dark:text-white">{user.displayName||'Customer'}</strong><span className="text-gray-500 dark:text-gray-400">{user.email}</span></td><td className="px-5 py-4 capitalize">{user.status}</td><td className="px-5 py-4 text-xs text-gray-500">Joined {new Date(user.createdAt).toLocaleDateString()}<br/>Active {user.lastActivityAt?new Date(user.lastActivityAt).toLocaleString():'Never'}</td><td className="px-5 py-4">{user.orderCount} / {user.requestCount}</td><td className="px-5 py-4">₹{Number(user.totalPaid).toLocaleString('en-IN')}</td><td className="px-5 py-4"><button onClick={()=>void change(user)} className={`rounded-lg px-3 py-2 text-xs font-bold ${user.status==='active'?'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-400':'bg-green-50 text-green-700 dark:bg-green-950/30 dark:text-green-400'}`}>{user.status==='active'?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div>}</div></div>;
};
export default CustomerUsersPage;
