import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { PlatformMetrics, platformService } from '@/services/platformService';

const empty:PlatformMetrics={visitorsToday:0,visitorsWeek:0,pageViews:0,anonymousSessions:0,activeSessions:0,registeredUsers:0,newUsersToday:0,totalRequests:0,pendingRequests:0,paidOrders:0,pendingOrders:0,failedOrders:0,revenue:0,readyDeliveries:0,pendingDeliveries:0,downloads:0,publishedAffiliateOffers:0,affiliateClicks:0,topTools:[],topProjects:[],topServices:[]};
const DashboardPage:React.FC=()=>{const [metrics,setMetrics]=useState(empty);const [error,setError]=useState('');useEffect(()=>{platformService.adminAnalytics().then(setMetrics).catch(reason=>setError(reason instanceof Error?reason.message:'Metrics unavailable.'));},[]);
 const cards=[['Visitors today',metrics.visitorsToday,'Unique anonymous/account sessions'],['Active recently',metrics.activeSessions,'Approx. active in last 5 minutes'],['Registered customers',metrics.registeredUsers,`${metrics.newUsersToday} new today`],['Requests',metrics.totalRequests,`${metrics.pendingRequests} pending`],['Paid orders',metrics.paidOrders,`${metrics.pendingOrders} pending payments`],['Paid revenue',`₹${metrics.revenue.toLocaleString('en-IN')}`,'Authoritative paid orders only'],['Ready deliveries',metrics.readyDeliveries,`${metrics.pendingDeliveries} preparing`],['Downloads',metrics.downloads,'Server-counted downloads'],['Published offers',metrics.publishedAffiliateOffers||0,'D1 affiliate recommendations'],['Affiliate clicks',metrics.affiliateClicks||0,'First-party trusted offer IDs']];
 const list=(title:string,rows:Array<{id:string;count:number}>)=><section className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><h2 className="font-black text-gray-950 dark:text-white">{title}</h2>{rows.length?<ol className="mt-4 space-y-3">{rows.map(row=><li key={row.id} className="flex justify-between text-sm"><span className="truncate text-gray-700 dark:text-gray-300">{row.id}</span><strong>{row.count}</strong></li>)}</ol>:<p className="mt-4 text-sm text-gray-500">No events yet.</p>}</section>;
 return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-black text-gray-950 dark:text-white">Platform overview</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Privacy-conscious first-party activity and authoritative D1 commerce metrics.</p></div><div className="text-right text-xs text-gray-500"><strong>{metrics.visitorsWeek}</strong> visitors in the last 7 days<br/><strong>{metrics.pageViews}</strong> total page views</div></div>{error&&<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-950/30 dark:text-amber-300">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title,value,note])=><div key={String(title)} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><p className="text-xs font-bold uppercase tracking-wide text-gray-500">{title}</p><p className="mt-2 text-3xl font-black text-gray-950 dark:text-white">{value}</p><p className="mt-2 text-xs text-gray-500 dark:text-gray-400">{note}</p></div>)}</div><p className="rounded-xl border border-gray-200 bg-white p-4 text-sm text-gray-600 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300"><strong>AdSense reporting not connected.</strong> Earnings are intentionally not estimated or shown as verified revenue.</p><div className="grid gap-5 lg:grid-cols-3">{list('Popular tools',metrics.topTools)}{list('Popular projects',metrics.topProjects)}{list('Popular services',metrics.topServices)}</div><div className="flex flex-wrap gap-3"><Link to="/admin/requests" className="rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-bold text-white">Review requests</Link><Link to="/admin/users" className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm font-bold dark:border-gray-700">Customer accounts</Link><Link to="/admin/affiliates" className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm font-bold dark:border-gray-700">Affiliate offers</Link><Link to="/admin/settings" className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm font-bold dark:border-gray-700">Site settings</Link></div></div>};
export default DashboardPage;
